---
# remove cloudera-manager.repo
- name: "remove cloudera-manager.repo"
  file:
    path: "/etc/yum.repos.d/cloudera-manager.repo"
    state: absent
  when: drop_old_cdh

# yum --downloadonly --downloaddir=/root/packages install xxx
- name: "install yum utils"
  yum:
    name: "yum-utils"
    state: present
  when: drop_old_cdh

- name: "cleanup old installation"
  shell: "yum-complete-transaction --cleanup-only"
  when: drop_old_cdh

# /etc/yum.repos.d/cloudera-repo.repo
# http://10.0.0.253:8000/files/cm5/repo-as-tarball/cm/5
- name: "Modifying Clients to Use the Internal Repository"
  template:
    src: "cloudera-repo.repo.j2"
    dest: "/etc/yum.repos.d/cloudera-repo.repo"

- name: "Uninstall the Cloudera Manager Server packages of [remove service： cloudera-manager-daemons]"
  yum:
    name: ["cloudera-manager-daemons", "cloudera-manager-server"]
    state: removed
  when: drop_old_cdh

- name: "Uninstall the Cloudera Manager Server packages of [reset-failed service]"
  shell: "systemctl reset-failed&&systemctl daemon-reload"
  when: drop_old_cdh

- name: "Uninstall the Cloudera Manager Server packages of [remove log files]"
  file:
    path: "/var/log/cloudera-scm-server/"
    state: absent
  when: drop_old_cdh

# sudo yum install cloudera-manager-daemons cloudera-manager-server
- name: "Install the Cloudera Manager Server [packages]/parcels"
  yum:
    name: ["cloudera-manager-daemons", "cloudera-manager-server"]
    state: present

- name: "Configure the Cloudera Manager Server's [JAVA_HOME] the installed place of get JAVA_HOME"
  shell: "unset JAVA_HOME&&source /etc/profile&&echo $JAVA_HOME"
  register: rlt_JAVA_HOME

- name: "Configure the Cloudera Manager Server's [JAVA_HOME] the installed place of debug JAVA_HOME"
  debug: var=rlt_JAVA_HOME

# /etc/default/cloudera-scm-server
- name: "Configure the Cloudera Manager Server's [JAVA_HOME] the installed place"
  lineinfile:
    path: "/etc/default/cloudera-scm-server"
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME="{{ rlt_JAVA_HOME.stdout }}"'