---

- name: "Modifying Clients to Use the Internal Repository"
  template:
    src: "cloudera-repo.repo.j2"
    dest: "/etc/yum.repos.d/cloudera-repo.repo"

- name: "Uninstall the Cloudera Manager Agent packages of [remove service： cloudera-manager-agent]"
  yum:
    name: ["cloudera-manager-agent"]
    state: removed
  when: drop_old_agent

# /var/lib/cloudera-scm-agent/cm_guid
- name: "clear cm_guid"
  file:
    path: "/var/lib/cloudera-scm-agent/cm_guid"
    state: absent

- name: "Uninstall the Cloudera Manager Agent packages of [reset-failed and daemon-reload]"
  shell: "systemctl reset-failed&&systemctl daemon-reload"
  when: drop_old_agent

# sudo yum install cloudera-manager-daemons cloudera-manager-agent
- name: "Install the Cloudera Manager agent"
  yum:
    name: ["cloudera-manager-daemons", "cloudera-manager-agent"]
    state: present

# configure the Cloudera Manager Agent to point to the Cloudera Manager Server
# /etc/cloudera-scm-agent/config.ini
#[General]
# Hostname of the CM server.
#server_host=localhost
# Port that the CM server is listening on.
#server_port=7182
- name: "Configure the Cloudera Manager Agent to [point to] the [Cloudera Manager Server] of [server_host]"
  lineinfile:
    path: "/etc/cloudera-scm-agent/config.ini"
    regexp: "^server_host="
    line: "server_host={{ server_host }}"

#- name: "Configure the Cloudera Manager Agent to [point to] the [Cloudera Manager Server] of [server_port]"
#  lineinfile:
#    path: "/etc/cloudera-scm-agent/config.ini"
#    regexp: "^server_port="
#    line: "server_port={{ server_port }}"

# /etc/cloudera-scm-agent/config.ini
# use_tls=1
- name: "Configure the Cloudera Manager Agent of [use_tls]"
  lineinfile:
    path: "/etc/cloudera-scm-agent/config.ini"
    regexp: "^use_tls="
    line: "use_tls={{ agent_use_tls }}"

# View swappiness
# /proc/sys/vm/swappiness
# Cloudera 建议将 /proc/sys/vm/swappiness 设置为最大值 10。当前设置为 60。
#
# Change temporary
# 使用 sysctl 命令在运行时更改该设置并编辑 /etc/sysctl.conf
# sysctl vm.swappiness=10
#
# Change Permanently
# /etc/sysctl.conf
# vm.swappiness=10
- name: "Change swappiness, temporary"
  shell: "sysctl vm.swappiness=10"

- name: "Change swappiness, permanently"
  lineinfile:
    path: "/etc/sysctl.conf"
    regexp: "^vm.swappiness="
    line: "vm.swappiness=10"

# DO NOT START AGENT, ORELSE WE CAN'T CONFIGURE THE INSTALLATION DATA PACKAGE.
# sudo systemctl start cloudera-scm-agent
- name: "Start the Agents"
  service:
    name: cloudera-scm-agent
    state: stopped
